import type { GovernedConstructKind } from './governance-gate.js';

export type PrimitiveIndex = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14;
export type PrimitiveStatus = 'landed' | 'shipped' | 'building' | 'asked';
export type FoundryEnforcement = 'active' | 'pending';
export type EngineDeclarationAwarenessStatus = 'emitted' | 'available_unused' | 'held' | 'adopt_backlog';
export type EnginePrimitiveConstructKind = GovernedConstructKind | 'arg_schema' | 'no_action_escape';

export interface EnginePrimitiveEntry {
  readonly computation_class: EnginePrimitiveConstructKind;
  readonly primitive_index: PrimitiveIndex;
  readonly primitive_name: string;
  readonly primitive_status: PrimitiveStatus;
  readonly pgas_ref: string;
  readonly request_ref: string;
  readonly foundry_enforcement: FoundryEnforcement;
  readonly since_engine_version?: string;
  readonly build_order_note?: string;
}

export interface EngineDeclarationAwarenessEntry {
  readonly construct: string;
  readonly status: EngineDeclarationAwarenessStatus;
  readonly note: string;
}

const CONVERGENCE_ALIGNMENT_REQUEST =
  'docs/curator-requests/2026-08-07-declarative-consumer-convergence-alignment.md';

export const ENGINE_DECLARATION_AWARENESS: readonly EngineDeclarationAwarenessEntry[] = [
  { construct: 'Specification.name', status: 'emitted', note: 'Generated specs set the program slug as the spec name.' },
  { construct: 'Specification.termination', status: 'emitted', note: 'The skeleton declares BoundedSession.' },
  { construct: 'Specification.topology', status: 'emitted', note: 'The skeleton declares CyclicTopology.' },
  { construct: 'Specification.preamble', status: 'emitted', note: 'The synthesizer writes a program-specific invariant preamble.' },
  { construct: 'Specification.modes', status: 'emitted', note: 'Synthesized mode records are emitted from the intake stage graph.' },
  { construct: 'Specification.initial', status: 'emitted', note: 'The first synthesized mode is assigned as initial.' },
  { construct: 'Specification.terminal', status: 'emitted', note: 'Terminal modes are derived from the synthesized topology.' },
  { construct: 'Specification.status_on_terminal', status: 'available_unused', note: 'No generator input selects terminal Failed/Completed overrides yet.' },
  { construct: 'Specification.channels', status: 'emitted', note: 'Generated specs declare input, output, document, delegation, and tool channels as needed.' },
  { construct: 'Specification.schema', status: 'emitted', note: 'The synthesizer declares durable schema paths for inputs, outputs, notebook state, delegation, documents, and verification.' },
  { construct: 'Specification.ingestion', status: 'emitted', note: 'Generated specs map trigger channels to declared input paths.' },
  { construct: 'Specification.ingestion_guidance', status: 'available_unused', note: 'Current generated programs use mode guidance, prompts, and recovery_steers instead.' },
  { construct: 'Specification.ingestion_root_passthrough', status: 'available_unused', note: 'No generated channel currently needs root passthrough wildcard ingestion.' },
  { construct: 'Specification.action_map', status: 'emitted', note: 'Every generated mode vocabulary action is backed by an action_map entry.' },
  { construct: 'Specification.repair_bound', status: 'emitted', note: 'The skeleton declares the global repair bound.' },
  { construct: 'Specification.fallback', status: 'emitted', note: 'The skeleton declares the fallback output channel and payload.' },
  { construct: 'Specification.guidance', status: 'emitted', note: 'The synthesizer emits mode guidance and toolkit guidance.' },
  { construct: 'Specification.prompts', status: 'emitted', note: 'The synthesizer emits per-mode prompt text.' },
  { construct: 'Specification.projection', status: 'emitted', note: 'The synthesizer emits mode-specific include/exclude projection profiles.' },
  { construct: 'Specification.view', status: 'emitted', note: 'Standalone generated programs serialize top-level view: sidecars consumed by loadProgramByConvention; existing-repo targets keep the residual ProgramEntry.viewProfile registration path. Anchors (verified against 6.6.1) are node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:5547-5568 (ViewSection 5547, ViewProfile 5555) and ProgramEntry.viewProfile/projectionBuilderMigration at 6043/6058. Parity-confirmed v5.6.0 #1014/#1023: the projection consolidation (routing.session + render projection selector) is opt-in/default-compatible, so emitted view:/render: sidecars stay byte-identical with no emission change.' },
  { construct: 'Specification.render', status: 'emitted', note: 'Standalone generated programs serialize top-level render: sidecars consumed by loadProgramByConvention for PDF-report deliverables; existing-repo targets keep the residual ProgramEntry.renderProfile registration path. Public anchors (verified against 6.6.1) are node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:5626-5834 (RenderProfile 5809, RenderSectionList 5724) and ProgramEntry.renderProfile at 6088.' },
  { construct: 'EngineCapability.render', status: 'adopt_backlog', note: 'v5.4.0/5.6.0 #992 render capability + engine-native ArtifactStore sink. NO ENGINE BLOCKER REMAINS -- all three gaps are closed and the remaining work is pure foundry emission. (1) GRAMMAR GAP CLOSED in 5.7.1: simodelne/pgas#1045 shipped RenderSectionList, so the per-approved-item docx class is declaratively expressible -- proven hermetically in tests/integration/render-section-list-falsifier.test.ts (S-1 positive; K-1/K-2 kill-proofs OBSERVED failing under sabotage: rebinding `from` makes the approved prose vanish, and an empty bucket renders ZERO sections and fabricates nothing). (2) AUTHOR-LESS DISPATCH GAP CLOSED in 6.0.0: simodelne/pgas#1054 shipped IntegrationHook.payload and createServerOutputAdapter forwards ONLY that payload for a non-EffectAction that owns one, so capability: render\'s exact {artifact_id} selector reaches renderCapability from a decision_only stage with no author round -- proven as P-1, which flips back to \'RenderProvider: request.format must be "docx"\' / 0 artifacts / session Failed when the payload line is removed. (3) DISPATCH-SCOPE GAP RESOLVED WITH EXISTING GRAMMAR, no engine change: simodelne/pgas#1086 was filed asking for IntegrationHook.mode/when and was CLOSED after an exhaustive audit found a shipped route. Integration hooks dispatch on exactly three events -- OnTransition (no filter), AfterRound (no filter, E-2), and AfterMutation (the ONLY scoped one; runAfterMutationHooks matches instructionSet.mutations against hook.path). Binding the hook AfterMutation to the one-shot <stage>.render_pending write that the generated program ALREADY owned, moved onto the loop-exit action, yields EXACTLY ONE dispatch with a content-complete deliverable and DELETES both the OnTransition reaction and the consumer-side dispatch filter. MEASURED ON THE REAL SYNTHESIZED CONFIRMATION-LOOP ARTIFACT (dispatch count is otherwise unobservable -- the engine does not log hook fires and a second dispatch overwrites the same result_path): 1 dispatch, section_count 3, terminal, no export-stage author round; KILL-PROOF reverting only the event to OnTransition gives 4 dispatches on that same artifact, so G-2 reproduces on the real class. Naive scopings stay dead and are kept as regression guards: G-2a an AfterMutation hook on a DERIVED path never fires (and the real export-entry aggregate guard IS derived), G-2b the collection path fires once per MAppend. REMAINING WORK IS FOUNDRY-SIDE ONLY: emit render: + capability: render + the AfterMutation-scoped hook, delete renderDocxExportStageBody/renderHtmlExportStageBody/sectionsFromDomain/sectionForDomainValue/approvedContentSectionsFromDomain from domain-synthesis.ts (which today FABRICATE a placeholder section and RE-DERIVE approval in TS), re-point assessExportEngagement at the engine-native ArtifactStore, then flip this entry to emitted. The OOXML byte serializer stays consumer-owned by design (the engine never bundles a renderer), collapsing to ONE generic RenderProvider. Anchors (verified against 6.6.1) _shared-types.d.ts:289-299 (IntegrationHook, payload at 295), 5809 (RenderProfile), 7191-7197 (ArtifactStore), 8862 (RenderProvider), 8964 (PgasServerConfig.renderProvider); runAfterMutationHooks/runAfterRoundHooks/runOnTransitionHooks at dist-bundle/create-server.mjs:8738/8777/8790. Requests: docs/curator-requests/2026-08-23-render-section-list-primitive.md (shipped), 2026-08-24-declarative-render-dispatch-author-less-stage.md (shipped), 2026-08-25-integration-hook-transition-scoping.md (CLOSED, resolved with existing grammar).' },
  { construct: 'Specification.integrations', status: 'emitted', note: 'Export decision-only stages emit integration hooks when needed. The export hook is declared AfterMutation and SCOPED to the one-shot <stage>.render_pending write carried by the transition INTO the export stage -- NOT OnTransition, which the engine batches on every mode change and which was measured minting one deliverable per hop (4 on the real confirmation-loop artifact). This scoping is what removed the consumer-side dispatch filter and the OnTransition render_pending reaction.' },
  { construct: 'IntegrationHook.payload', status: 'adopt_backlog', note: 'v6.0.0 simodelne/pgas#1054 adds a static IntegrationHook.payload (_shared-types.d.ts:289-299, payload at 295; verified against 6.6.1) dispatched INSTEAD of the engine\'s {action, event, domain} envelope -- the only way an author-less decision_only stage can supply an engine capability\'s selector. PROVEN hermetically as P-1 in tests/integration/render-section-list-falsifier.test.ts (a decision_only stage mints a first-class artifactType:"render" docx with no author round). Not emitted yet only because the docx render migration it exists for is still foundry-side work; its former blocker (hook dispatch scope) is RESOLVED with existing grammar -- the emitted export hook is now AfterMutation-scoped to the one-shot <stage>.render_pending write, see EngineCapability.render.' },
  { construct: 'Specification.reactions', status: 'emitted', note: 'Generated specs emit declarative reactions with write scopes.' },
  { construct: 'Specification.features', status: 'emitted', note: 'The synthesizer emits required feature flags from generated capabilities.' },
  { construct: 'Specification.reference_data', status: 'available_unused', note: 'v5.2.0 #980 exposes declarative reference_data entries as pure domain data materialized under the reserved read-only reference.* namespace and read through source_path predicates; current generator audit found no hardcoded generated-program TS domain reference set to migrate, so this stays register-only/emit-on-demand. Anchors (verified against 6.6.1) node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:1150 (ReferenceEntryDecl), 2333 (Specification.reference_data), 3383 (raw).' },
  { construct: 'Specification.policies', status: 'emitted', note: 'Standalone generated programs serialize top-level policies: sidecars for delegationPolicy, artifactPolicy, syncOutContinuationPolicy, and queryPolicy, and loadProgramByConvention maps them onto ProgramEntry fields. Existing-repo targets keep minimal residual registration wiring. Anchors (verified against 6.6.1) are node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:3789/3805/3913/3918/3941 (RetryBudget/RoundBudget/Query/DenialTracking/ContentScan policies), 5853 (ProgramQueryPolicy), 5993 (ProgramReliabilityPolicy), 6889 (RiskPolicy), and RegisterProgramByConventionOptions at 10038-10111.' },
  { construct: 'Specification.import', status: 'emitted', note: 'v4.12 #917 file loaders and loadProgramByConvention resolve import: fragments and force strict blueprint validation on imported specs; generated programs emit a root import: manifest plus canonical blueprint block YAML files. Anchors (verified against 6.6.1) node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:5122-5131 (SpecWiringValidationOptions) and plugin.mjs import diagnostics.' },
  { construct: 'SpecWiringValidationOptions.blueprint', status: 'emitted', note: 'v4.12 #917 exposes blueprint modes off|warn|strict; synthesized program validation and generated runtime helpers can request blueprint:off, but import: specs are still assembled and validated strict by the engine. Anchor (verified against 6.6.1) node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:5122-5131 (blueprint at 5131).' },
  { construct: 'Specification.finalization_requires', status: 'available_unused', note: 'Completion is currently expressed through transition guards and schema facts, not finalization_requires.' },
  { construct: 'Specification.finalization_gated_actions', status: 'available_unused', note: 'No generated action opts into finalization_requires as implicit preconditions yet.' },
  { construct: 'Specification.artifact_bundle', status: 'available_unused', note: 'The generator currently emits ProgramEntry artifactPolicy for exports instead of spec artifact_bundle.' },
  { construct: 'Specification.schema_invariants', status: 'emitted', note: 'Document fidelity emits record-level content invariants. Parity-confirmed v5.6.0 #976: the engine now validates nested schema_invariants on ancestor mutations, strengthening the foundry-emitted invariants with no emission change.' },
  { construct: 'Specification.bounded_rework', status: 'available_unused', note: 'Available in v4.2.0; no generated per-loop regress action/counter contract uses it yet.' },
  { construct: 'Specification.keyed_collections', status: 'emitted', note: 'Persistence-oriented generated programs emit keyed_collections for engine-owned upsert dedupe. Aligned to v5.6.0 #993: a keyed/merge MAppend upserts ONE element by key and the loader infers its from_arg as the ELEMENT (object) type, so a keyed record_array field is presented element-typed and appended one-record-per-call through a repeatable append action (append_<stage>_<field>) — NOT a batch array on the one-shot terminal action (a wrapping array never resolves the key). Non-keyed record_array MAppend keeps the #825 whole-array (array) shape. See src/foundry-program/synthesizer/topology.ts (actionMapEntryFor + isKeyedRecordArrayField) and applyKeyedRecordArrayAppendActions in synthesizer.ts.' },
  { construct: 'Specification.recovery_steers', status: 'emitted', note: 'Confirmation loops emit recovery steers, including set/template_paths variants.' },
  { construct: 'Specification.merge_collections', status: 'available_unused', note: 'Registered as primitive index 10, but no content-key reducer emitter exists yet.' },
  { construct: 'Specification.no_action_escapes', status: 'emitted', note: 'Confirmation-loop synthesis emits no_action_escapes at src/foundry-program/synthesizer.ts with engine-owned counter/arm paths, no_action_escape feature flag, and blocked-route guards/preconditions.' },
  { construct: 'Specification.mandatory_delegations', status: 'adopt_backlog', note: 'Phase D backlog: v4.4 compiled mandatory_delegations is derived from mode requires_delegations and gated by mandatory_delegation; public type anchors (verified against 6.6.1) node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:1380 (MandatoryDelegationDecl), 1406 (MandatoryDelegation), 2371 (Specification.mandatory_delegations).' },
  { construct: 'Specification.confirmation_pairing', status: 'emitted', note: 'Confirmation loops emit pairing prefixes, policy, and terminal actions.' },
  { construct: 'Specification.proceeds_to', status: 'emitted', note: 'Generated transition actions emit v5 proceeds_to targets.' },
  { construct: 'Specification.notice_terminal_exemptions', status: 'available_unused', note: 'No generated action currently needs notice-terminal rewrite exemption.' },
  { construct: 'Specification.derived_paths', status: 'emitted', note: 'Collection lifecycles, confirmation loops, flat stage-output mirrors, and delegation settle flags emit derived path rules.' },
  { construct: 'Specification.derived_state_machines', status: 'available_unused', note: 'No generated stage currently uses engine-owned state-machine derivation.' },
  { construct: 'Specification.collection_finalizers', status: 'available_unused', note: 'No generator surface maps collection cleanup pipelines to finalizers yet.' },
  { construct: 'Specification.collection', status: 'available_unused', note: 'v5 keeps singular PGAS-L collection blocks; the foundry emits scattered primitives directly rather than PGAS-L collection blocks. Anchor (verified against 6.6.1) node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:3540-3648.' },
  { construct: 'PGAS-L.collection', status: 'available_unused', note: 'v5 PGAS-L uses singular collection blocks and unified Predicate grammar across derived_paths, collection_finalizers, and DSM transitions. Generated specs continue to emit explicit keyed_collections, schema_invariants, derived_paths, and collection_finalizers surfaces.' },
  { construct: 'ObjectFanOut', status: 'available_unused', note: 'v4.12 exports ObjectFanOutConfig/ObjectFanOutField and makeObjectFanOutHandler for object fan-out reactions; generated document fan-out still emits explicit delegation logic in this phase. Anchors (verified against 6.6.1) node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:9690-9698 and plugin.d.ts:64-65,195.' },
  { construct: 'Specification.tools', status: 'emitted', note: 'Registered web_search tool declarations are emitted from stage tool descriptors.' },
  { construct: 'EngineCapability.web_search', status: 'adopt_backlog', note: 'Phase D/E backlog: WebSearchProvider is exported from plugin.js for engine-capability search; foundry still emits per-program registered web_search tool adapters and does not wire the engine capability in Phase B (anchors verified against 6.6.1: _shared-types.d.ts:9913-9916 WebSearchProvider and plugin.d.ts:163).' },
  { construct: 'EngineCapability.document_extraction', status: 'adopt_backlog', note: 'v4.9 #926 exposes the document_extraction engine capability through the stripped channel capability sidecar; foundry still emits its document extraction upload/delegation/self-contained surfaces and leaves capability adoption to a later phase. ANCHOR FINDING (6.6.1): no declaration named document_extraction/documentExtraction/DocumentExtraction exists in _shared-types.d.ts (0 grep hits for document_extraction|documentExtraction|DocumentExtraction); the capability is bound by string name through CapabilityBindingMap (8902) / ConfiguredCapabilityBinding (8904), so this entry has no type-level anchor to cite.' },
  { construct: 'EngineCapability.audio_transcription', status: 'available_unused', note: 'v5.6.0 #1003 engine capability sidecar + consumer AudioTranscriptionProvider, analogous to web_search/document_extraction (both adopt_backlog); no generated program ingests audio; expose-on-demand by parity. Anchors (verified against 6.6.1) node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:8808-8850 (AudioTranscriptionProviderInput 8808, AudioTranscriptionResult 8818, AudioTranscriptionProvider 8837) and PgasServerConfig.audioTranscriptionProvider 8972.' },
  { construct: 'EngineCapability.surrogate_target_response', status: 'available_unused', note: 'v5.6.0 #999/#1000 surrogate/monitor INFRA capability (surrogateProgram/internal, UserSurrogateService.triggerBoundTarget/completeFromBoundTargetTerminal); N-A to the governed document/research/extraction/delegation programs the foundry synthesizes. Anchors (verified against 6.6.1) node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:5961/5968 (ProgramCapabilities.surrogateProgram/internal), 5980 (ProgramSurrogatePolicy), 7616 (completeFromBoundTargetTerminal), 8310-8358 (UserSurrogateServiceOptions/triggerBoundTarget). 6.5.0 simodelne/pgas#1147 (CLOSED 2026-08-31) added the declarative policies.surrogateProgramPolicy: { enabled } catalog marker mapping 1:1 onto ProgramEntry.capabilities.surrogateProgram (no new d.ts type); N-A for the same reason.' },
  { construct: 'Specification.pure', status: 'emitted', note: 'Generated specs start from the pure skeleton and can set pure=false for decision-only export stages.' },
  { construct: 'Specification.pure:strict', status: 'adopt_backlog', note: 'Phase F backlog: strict pure contract requires the pure_strict feature and forbids handler-style reactions per node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:2447-2452 (raw 3651-3655; verified against 6.6.1); adoption is per-program-gated. The former fan-out blocker is GONE: the per-item delegation-fan-out ask simodelne/pgas#922 was CLOSED 2026-08-24 and shipped in v5.7.0, and 6.6.1 exposes Feature.fan_out_delegation (315), FanOutDelegation (1128-1139) and Specification.fan_out_delegations (2321, raw 3359). The foundry does NOT emit fan_out_delegations yet (0 hits in src/ and templates/), so fan-out programs still carry explicit delegation logic and their strict adoption is foundry-side work, not an engine dependency.' },
  { construct: 'Feature.pure_strict', status: 'adopt_backlog', note: 'Phase F backlog: v4.5 Feature includes pure_strict; Feature union at node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:315 (verified against 6.6.1); per-program gating is required. Fan-out programs no longer wait on an engine ask: simodelne/pgas#922 shipped fan_out_delegation in v5.7.0 (see Specification.fan_out_delegations); what remains is the foundry emitter.' },
  { construct: 'Feature.merge_collection', status: 'available_unused', note: 'v4.5 Feature includes merge_collection (Feature union at node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:315, verified against 6.6.1), but foundry uses keyed_collections and has no content-key merge emitter.' },
  { construct: 'Feature.reference_data', status: 'available_unused', note: 'v5.2.0 #980 Feature includes reference_data (Feature union at node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:315, verified against 6.6.1); current generated programs do not need a reference_data block, but the foundry may emit it when a real domain vocabulary, denylist pattern set, or keyed rule set would otherwise be generated as TS.' },
  { construct: 'Specification.disallow_raw_mutation_authoring', status: 'available_unused', note: 'No generated program opts into the stricter raw mutation authoring policy yet.' },
  { construct: 'Specification.command_grammar', status: 'available_unused', note: 'Generated programs use control_plane vocabulary rather than command_grammar.' },
  { construct: 'Specification.control_plane', status: 'emitted', note: 'The skeleton declares the control plane and the synthesizer rewrites the entry trigger channel.' },
  { construct: 'Specification.ephemeral', status: 'available_unused', note: 'Generated specs use durable schema/projection rather than ephemeral state cells.' },
  { construct: 'Specification.advisory_schema', status: 'emitted', note: 'Skill catalog synthesis emits advisory paths for activation bodies.' },
  { construct: 'Specification.activation_providers', status: 'emitted', note: 'Skill catalog synthesis emits activation provider targets.' },
  { construct: 'Specification.decision_schema', status: 'emitted', note: 'Skill triage emits a decision-zone schema path.' },
  { construct: 'Specification.agent_nodes', status: 'available_unused', note: 'No generated program declares agent-network nodes yet.' },
  { construct: 'Specification.schedule', status: 'available_unused', note: 'No generated program declares scheduled background ticks yet.' },
  { construct: 'Specification.initial_crystallize', status: 'available_unused', note: 'No generator surface currently selects session-creation cache crystallization.' },
  { construct: 'Specification.initial_trigger', status: 'available_unused', note: 'Create-time route sugar exists in v4.2.0; generated scaffolds seed sessions through ordinary triggers today.' },
  { construct: 'Mode.requires_delegations', status: 'adopt_backlog', note: 'Phase D backlog: v4.4 raw mode requires_delegations gates mode exit on real delegation dispatch; public anchors (verified against 6.6.1) are node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:3099 (raw requires_delegations), 1484 (Mode.requiresDelegations), 1380 (MandatoryDelegationDecl).' },
  { construct: 'Channel.direction', status: 'emitted', note: 'All generated channels declare In or Out direction.' },
  { construct: 'Channel.sync', status: 'emitted', note: 'All generated channels declare Sync or Async synchronicity.' },
  { construct: 'Channel.structured_decision', status: 'emitted', note: 'User confirmation channels declare structured_decision for approval loops.' },
  { construct: 'Channel.decision_targeting', status: 'emitted', note: 'Confirmation loops emit decision targeting over the active collection item.' },
  { construct: 'Channel.durable', status: 'emitted', note: 'Conversational hub entry channels opt into durable delivery.' },
  { construct: 'Channel.durability', status: 'emitted', note: 'Durable conversational hub channels declare retry and ordering policy.' },
  { construct: 'Channel.target_spec', status: 'emitted', note: 'Delegation channels declare child target specs.' },
  { construct: 'Channel.delegation_mode', status: 'available_unused', note: 'The foundry currently emits blocking delegation and rejects continue-mode delegation.' },
  { construct: 'DelegationMode.conversational', status: 'adopt_backlog', note: 'Phase D backlog: v4.4 DelegationMode includes conversational and caller inbox fields for bidirectional child questions; public anchors (verified against 6.6.1) are node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:617 (DelegationMode) and 707-719 (Channel.callerInboxChannel/Path/Answer).' },
  { construct: 'Channel.result_path', status: 'emitted', note: 'Delegation channels declare where child results land.' },
  { construct: 'Channel.result_schema', status: 'available_unused', note: 'v4.9 #921 flat-materializes declared delegation result_schema fields under result_path so view: can read typed child-result leaves; generated delegation schema is still declared in Specification.schema, not Channel.result_schema.' },
  { construct: 'Channel.dynamic_target_arg', status: 'available_unused', note: 'Dynamic delegation targets are rejected by the current v1 delegation validator.' },
  { construct: 'Channel.max_delegated_rounds', status: 'emitted', note: 'Delegation children may emit per-child max delegated rounds.' },
  { construct: 'Channel.reacquire_timeout_ms', status: 'available_unused', note: 'No generator input exposes parent lock reacquire timeout overrides.' },
  { construct: 'Channel.round_timeout_ms', status: 'emitted', note: 'Delegation children may emit per-child round timeout.' },
  { construct: 'Channel.optional', status: 'emitted', note: 'Generated delegation channels are optional/degrade-only.' },
  { construct: 'Channel.mcp_connector', status: 'available_unused', note: 'Registered tools use the tool registry path, not mcp_connector channel declarations.' },
  { construct: 'Channel.message_type', status: 'available_unused', note: 'No generated agent-network or typed-channel fabric uses message_type yet.' },
  { construct: 'Channel.delivery_policy', status: 'available_unused', note: 'No generated typed-channel fabric uses delivery_policy yet.' },
  { construct: 'Channel.capabilities', status: 'available_unused', note: 'No generated typed-channel fabric declares channel capability tokens yet.' },
  { construct: 'Channel.ttl_ms', status: 'available_unused', note: 'No generated channel currently declares TTL.' },
  { construct: 'Channel.max_subscribers', status: 'available_unused', note: 'No generated broadcast/subscription channel declares subscriber caps.' },
  { construct: 'Predicate.FieldTruthy', status: 'emitted', note: 'Generated guards and preconditions use truthy checks.' },
  { construct: 'Predicate.FieldFalsy', status: 'emitted', note: 'Generated guards and preconditions use falsy checks.' },
  { construct: 'Predicate.FieldEquals', status: 'emitted', note: 'The foundry spec and generated specs use equality guards.' },
  { construct: 'Predicate.FieldEqualsField', status: 'available_unused', note: 'No generator descriptor emits cross-field equality yet.' },
  { construct: 'Predicate.FieldLessThan', status: 'emitted', note: 'Numeric aggregate predicates can emit this kind from collection lifecycle descriptors.' },
  { construct: 'Predicate.FieldLessOrEqual', status: 'emitted', note: 'Numeric aggregate predicates can emit this kind from collection lifecycle descriptors.' },
  { construct: 'Predicate.FieldGreaterThan', status: 'emitted', note: 'Numeric aggregate predicates can emit this kind from collection lifecycle descriptors.' },
  { construct: 'Predicate.FieldGreaterOrEqual', status: 'emitted', note: 'Document fidelity and numeric aggregate predicates emit this kind.' },
  { construct: 'Predicate.FieldContainsAll', status: 'emitted', note: 'Document fidelity emits token-coverage predicates.' },
  { construct: 'Predicate.FieldContainsAllFromCollection', status: 'available_unused', note: 'v5.6.0 #1006 dynamic required-token coverage - required-token set read from a World array path (vs the static literal the foundry emits via FieldContainsAll from documents.fidelity_floor.required_tokens); no generated program authors runtime required tokens; emit-on-demand. Anchors (verified against 6.6.1) node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:268 (PredicateKind) and 983 (Predicate.source_path).' },
  { construct: 'Predicate.FieldMatchesPattern', status: 'emitted', note: 'Document schema invariants emit required-pattern predicates.' },
  { construct: 'Predicate.FieldNotMatchesPattern', status: 'emitted', note: 'Document schema invariants emit forbidden-pattern predicates.' },
  { construct: 'Predicate.FieldSourceGrounded', status: 'emitted', note: 'Document schema invariants emit source-grounding predicates.' },
  { construct: 'Predicate.FieldKeyedSourceSpan', status: 'available_unused', note: 'v5.6.0 #1005 schema-invariant-only leaf; proves a governed subject record cites exactly one durable source record by a typed key join AND its evidence is a contiguous verbatim span; strictly stronger than the emitted FieldSourceGrounded token-subset grounding; no generated program models keyed subject to source-record citations and no filed gap requires it; emit-on-demand. Anchors (verified against 6.6.1) node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:268 (PredicateKind) and 983-1010 (subject_key_path 988, subject_join_path 993, source_key_path 998, source_text_path 1003). 6.6.1 simodelne/pgas#1218 added the optional span_normalization: legal-text-v1 profile (1010, raw 2769) plus normalizeSourceSpan() in plugin.js; still N-A while this predicate is unused.' },
  { construct: 'Predicate.FieldInCollection', status: 'available_unused', note: 'No generator descriptor emits collection membership predicates yet.' },
  { construct: 'Predicate.CollectionSubset', status: 'available_unused', note: 'No generator descriptor emits subset predicates yet.' },
  { construct: 'Predicate.PreviousItemFieldEquals', status: 'emitted', note: 'Confirmation-loop cursor preconditions emit previous-item predicates.' },
  { construct: 'Predicate.AllNodesStatus', status: 'available_unused', note: 'No generated agent-network workflow emits node-status predicates yet.' },
  { construct: 'Predicate.AllItemsStatus', status: 'emitted', note: 'Collection lifecycle completion preconditions emit all-items status predicates.' },
  { construct: 'Predicate.EventEmitted', status: 'available_unused', note: 'Generated transitions currently use field and trigger predicates instead.' },
  { construct: 'Predicate.TriggerType', status: 'emitted', note: 'The foundry spec uses trigger-type preconditions for confirmation and system-entry rounds.' },
  { construct: 'Predicate.All', status: 'emitted', note: 'Document fidelity and recovery steers compose predicates with All.' },
  { construct: 'Predicate.Any', status: 'emitted', note: 'Optional document upload guards compose skip/upload alternatives with Any.' },
  { construct: 'Predicate.Implies', status: 'emitted', note: 'Confirmation-loop cursor preconditions emit Implies.' },
  { construct: 'Predicate.Always', status: 'available_unused', note: 'v4.10.0 #836 added Always to PredicateKind (its 23rd member at the time; the 6.6.1 union has 29) for explicit unconditional predicates; foundry already uses derived_paths when.always and has no guard/precondition emitter that needs a Predicate.Always leaf yet. Anchor (verified against 6.6.1) node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:268.' },
  { construct: 'Predicate.StringLengthLessThan', status: 'available_unused', note: 'v5.2.0 adds StringLengthLessThan to PredicateKind with max as the exclusive string length upper bound; no generated descriptor currently needs this predicate. Anchors (verified against 6.6.1) node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:268 and max docs at 1077-1085.' },
  { construct: 'Predicate.FieldMatchesNoneOfPatternSet', status: 'available_unused', note: 'v5.2.0 adds FieldMatchesNoneOfPatternSet to PredicateKind for source_path-backed pattern-set checks, intended to pair with reference_data denylist pattern sets when emitted; current generator audit found no hardcoded generated-program TS denylist to migrate. Anchor (verified against 6.6.1) node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:268.' },
  { construct: 'RawPredicate.membership_sugar', status: 'available_unused', note: 'v5 replaces retired raw membership sugar with Any([FieldEquals...]) predicates; generated specs use typed PredicateKind vocabulary.' },
  { construct: 'Predicate.FieldNe', status: 'held', note: 'Not present in the PredicateKind type surface (verified against 6.6.1, _shared-types.d.ts:268); do not emit unless the engine adds it.' },
  { construct: 'Predicate.Not', status: 'held', note: 'Not present in the PredicateKind type surface (verified against 6.6.1, _shared-types.d.ts:268); use shipped combinators only.' },
  { construct: 'action_map.mutations', status: 'emitted', note: 'Generated action_map entries emit declared mutations.' },
  { construct: 'action_map.mutations.from_arg', status: 'emitted', note: 'Generated actions source values from named tool-call args.' },
  { construct: 'action_map.mutations.from_state', status: 'emitted', note: 'Document-slice and delegated child specs source values from projected state.' },
  { construct: 'action_map.mutations.coerce', status: 'available_unused', note: 'No generated mutation currently needs declared value coercion.' },
  { construct: 'action_map.bounds', status: 'available_unused', note: 'ActionSemantics supports bounds, but generated YAML does not declare bounds today.' },
  { construct: 'action_map.channel', status: 'emitted', note: 'Generated action_map entries declare terminal effect channels.' },
  { construct: 'action_map.result_path', status: 'emitted', note: 'Stage, artifact-plan, verification, collection, document, and delegation actions emit result paths when needed.' },
  { construct: 'action_map.query_path', status: 'available_unused', note: 'Available for fixed-path query actions; generated specs rely on ProgramEntry queryPolicy instead.' },
  { construct: 'action_map.is_query', status: 'available_unused', note: 'Available for dynamic query actions; no generated action maps to QueryAction today.' },
  { construct: 'action_map.description', status: 'emitted', note: 'Generated action_map entries include tool-facing descriptions.' },
  { construct: 'action_map.arg_descriptions', status: 'emitted', note: 'Generated LLM reasoning, notebook, verification, and delegation actions emit arg descriptions.' },
  { construct: 'action_map.arg_schema', status: 'emitted', note: 'Contracted reasoning action args emit arg_schema at src/foundry-program/synthesizer/topology.ts:283; notebook pin/unpin key args emit arg_schema at src/foundry-program/synthesizer.ts:2542; confirmation-loop proposal content args emit arg_schema at src/foundry-program/synthesizer.ts:3789. simodelne/pgas#1116 (6.2.0 regression: delegated child never reached terminal because sentinel type hints on any-typed capture paths such as <mode>.raw_result_json were promoted to runtime contracts by fe2c6d3e #1108; CLOSED 2026-08-29) is FIXED by d4d85188 "fix(drivers): preserve sentinel-only tool argument hints (#1121)" shipped in v6.2.1 -- sentinel-only hints on any/undeclared paths are presentation hints, while authored arg_schema stays enforced.' },
  { construct: 'action_map.continues', status: 'available_unused', note: 'No generated terminal action opts into forced auto-continue metadata.' },
  { construct: 'action_map.awaits_user_decision', status: 'emitted', note: 'Artifact planning, document upload, and confirmation loops park automation for user decisions.' },
  { construct: 'derived_paths.first_item_where_field_ne', status: 'emitted', note: 'Confirmation loops emit first-not-done cursor derivation.' },
  { construct: 'derived_paths.all_items_field_eq', status: 'emitted', note: 'Collection lifecycle completion emits universal equality derivation.' },
  { construct: 'derived_paths.any_item_field_eq', status: 'emitted', note: 'Confirmation loops emit existential proposed-item flags.' },
  { construct: 'derived_paths.items_where_field_eq', status: 'emitted', note: 'Confirmation loops emit status bucket partitions. simodelne/pgas#1087 (items_where_field_eq returned [] for storage.representation indexed_array; CLOSED 2026-08-27) is FIXED: aea4f7ac "fix(runtime): materialize indexed collections for derived reads (#1095)" shipped in v6.1.2, hardened by 2ad88036 "fix(runtime): align derived read representations (#1104)" in v6.2.0 -- #1095 is the fixing PR number, not a separate issue.' },
  { construct: 'derived_paths.sum_of', status: 'emitted', note: 'Collection lifecycle numeric sums emit sum_of derivation.' },
  { construct: 'derived_paths.from_predicate', status: 'emitted', note: 'Plain delegation settle flags derive settled/degraded booleans from child result status predicates.' },
  { construct: 'derived_paths.count_of', status: 'emitted', note: 'PDF report render adoption derives report row counts from typed stage result collections; collection-lifecycle synthesis still uses its narrower status/count guards directly.' },
  { construct: 'derived_paths.concat', status: 'available_unused', note: 'No generated descriptor needs string concatenation derivation yet.' },
  { construct: 'derived_paths.field_value', status: 'emitted', note: 'Demand-driven flat stage-output mirrors copy <stage>.output.result_json/items_json into legacy flat paths through field_value rules.' },
  { construct: 'derived_paths.now_iso', status: 'available_unused', note: 'Generated programs currently use handlers/runtime values for timestamps.' },
  { construct: 'derived_paths.current_round', status: 'available_unused', note: 'Generated programs do not persist the current round via derived_paths yet.' },
  { construct: 'derived_paths.min_of', status: 'adopt_backlog', note: 'v4.10.0 #836 SetMinOf computes the minimum numeric field across a collection; foundry does not yet have a min-report or min-threshold descriptor. Anchors (verified against 6.6.1) node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:1945 (DerivedPathSetKind) and raw YAML set kind at 3458.' },
  { construct: 'derived_paths.max_of', status: 'adopt_backlog', note: 'v4.10.0 #836 SetMaxOf computes the maximum numeric field across a collection; foundry does not yet have a max-report or max-threshold descriptor. Anchors (verified against 6.6.1) node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:1945 (DerivedPathSetKind) and raw YAML set kind at 3458.' },
  { construct: 'derived_paths.join_from', status: 'adopt_backlog', note: 'v4.10.0 #836 exposes join_from-style membership filtering as items_where_field_in_collection: keep source rows whose field appears in a second collection. Phase C uses it narrowly for refused/skipped report audit filtering; broader join descriptor sugar remains backlog. Anchors (verified against 6.6.1) node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:1945 (DerivedPathSetKind) and source_path/source_item_path at 2023/2030.' },
  { construct: 'collections.invariant_require_on', status: 'available_unused', note: 'v4.10.0 #836 PGAS-L collection sugar can express per-record invariants with collection require:; foundry still emits schema_invariants directly. ANCHOR FINDING (6.6.1): the only declaration is the per-record `require?: RawPredicate | RawPredicate[]` at node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:3583 inside the PGAS-L collection block 3540-3648 (compiles to schema_invariants); no declaration named require_on / item_requires exists in 6.6.1 _shared-types.d.ts (0 grep hits for require_on|requireOn|item_requires), so the aggregate on-style form this entry was named for is not in the shipped grammar.' },
  { construct: 'ProgramEntry.delegationPolicy', status: 'emitted', note: 'Standalone programs emit policies.delegationPolicy and convention loading maps it onto ProgramEntry; existing-repo targets keep residual registration wiring for child routing and input enrichment.' },
  { construct: 'ProgramDelegationPolicy.inputEnrichment', status: 'emitted', note: 'v5.3.1 #986 exposes DelegationInputEnrichment[] on ProgramDelegationPolicy for selective forwarding from parent inputs.<path> into delegated child seeds. Foundry emits policies.delegationPolicy.inputEnrichment from delegation payload_map, keeps request.* and domain_context.* on their legacy child seed routes, and normalizes other child roots to inputs.<path> so contract-revision document_intake/answers payloads are not silently dropped. Anchors (verified against 6.6.1) node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:816/829 (DelegationSessionFactory inputEnrichment, DelegationInputEnrichment) and ProgramDelegationPolicy.inputEnrichment at 5888-5891.' },
  { construct: 'ProgramEntry.artifactPolicy', status: 'emitted', note: 'Standalone programs emit policies.artifactPolicy and convention loading maps it onto ProgramEntry; existing-repo targets keep residual registration wiring for export surfaces.' },
  { construct: 'ProgramEntry.queryPolicy', status: 'emitted', note: 'Standalone programs emit policies.queryPolicy and convention loading maps it onto ProgramEntry; existing-repo targets keep residual registration wiring for enforce-mode query policy over declared projection paths.' },
  { construct: 'ProgramEntry.reliabilityPolicy', status: 'adopt_backlog', note: 'Phase E backlog: ProgramEntry can carry ProgramReliabilityPolicy retry/round/denial budgets at node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:5993-5997 with ProgramEntry.reliabilityPolicy at 6014 (verified against 6.6.1); Phase B emits no reliability policies.' },
  { construct: 'ProgramEntry.reactionHandlers', status: 'emitted', note: 'Standalone convention helpers pass generated reaction handlers through RegisterProgramByConventionOptions.reactionHandlers; existing-repo targets keep residual registration wiring.' },
  { construct: 'ProgramEntry.syncOutContinuationPolicy', status: 'emitted', note: 'Standalone programs emit policies.syncOutContinuationPolicy for registered tool channels and convention loading maps it onto ProgramEntry; existing-repo targets keep residual registration wiring.' },
  { construct: 'registerProgramByConvention', status: 'emitted', note: 'v5.x publishes registerProgramByConvention/loadProgramByConvention through the public plugin entrypoint. Standalone generated programs no longer emit registration.ts and build entries through the public convention loader; child delegationResultPolicy remains a minimal entryOverrides residual because it has no convention sidecar home. Anchors (verified against 6.6.1) node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:10132-10135 (loadProgramByConvention/registerProgramByConvention and, since 6.5.0 simodelne/pgas#1144, loadProgramFamilyByConvention/registerProgramFamilyByConvention) and plugin.d.ts:187-188,202-203; declarative manifest:/presentation:/registrations: sidecars are tracked under ProgramEntry.manifest, ProgramEntry.presentation and ConventionProgramFamilyLoad.registrations.' },
  // 6.0.0 -> 6.6.1 grammar additions (anchors verified against the installed 6.6.1 _shared-types.d.ts, 12293 lines).
  { construct: 'Specification.fan_out_delegations', status: 'adopt_backlog', note: 'v5.7.0 simodelne/pgas#922 (the foundry\'s own per-item delegation-fan-out ask; CLOSED 2026-08-24) shipped an engine-driven fan-out: FanOutDelegation binds mode/action/channel, sourceCollection/sourceKey, itemTarget, resultKeyPath/resultSink/resultField and completionPath so cursor + keyed sink + completion are one declaration. Anchors node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:1128-1139 (FanOutDelegation), 2321 (Specification.fan_out_delegations), 3359 (raw). NOT EMITTED today (0 hits for fan_out_delegation in src/ and templates/); generated document fan-out still emits explicit delegation logic (see ObjectFanOut). Emission opportunity: replace the explicit per-item delegation cursor/sink/completion trio in fan-out programs with one fan_out_delegations entry, which also unblocks pure:strict for them. Request: docs/curator-requests/2026-08-13-per-item-delegation-fanout-primitive.md.' },
  { construct: 'Feature.fan_out_delegation', status: 'adopt_backlog', note: 'v5.7.0 simodelne/pgas#922 Feature flag gating Specification.fan_out_delegations; Feature union at node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:315 (verified against 6.6.1). Not emitted (0 hits); flips together with Specification.fan_out_delegations when the foundry emitter lands.' },
  { construct: 'action_map.mutations.MReplace', status: 'adopt_backlog', note: 'v6.6.1 simodelne/pgas#1185 (CLOSED 2026-09-04; S-13) adds MReplace as the sixth MutationOp: atomic whole-array replacement/reset of an exact ArrayType path, presented like the #825 MAppend record-array param and emitted as ONE MutationAction; rejected at load on keyed_collections/merge_collections paths; MReplace [] is the sanctioned array reset (MClear stays for object paths). Anchors node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:278-286 (MUTATION_OPS, MReplace at 284, MutationOp 286). NOT EMITTED today (0 hits for MReplace in src/ and templates/): non-keyed record_array reasoning fields use the #825 whole-array MAppend at src/foundry-program/synthesizer/topology.ts:293-300 and tolerant captures MSet into any-typed containers (synthesizer.ts:769-781). Emission opportunity: emit MReplace for whole-array record_array results and for list-valued paths that must be set atomically, retiring the object/any-typed MSet escape hatch.' },
  { construct: 'action_map.mset_must_change', status: 'available_unused', note: 'v6.6.0 simodelne/pgas#1209 (CLOSED 2026-09-03; PR #1210 MERGED) adds the opt-in per-action content-progress marker: with mset_must_change: true the recognizer rejects an MSet whose proposed value equals the stored value through the new GateKind GKContentProgress and repairs, never mutates; absent/false is byte-identical. Anchors node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:287 (GateKind), 1662-1666 (ActionSemantics.mset_must_change), 3224 (raw). Not emitted (0 hits for mset_must_change/GKContentProgress in src/ and templates/). Emission opportunity: set it on confirmation-loop revise/proposal MSet actions so a byte-identical re-proposal is repaired instead of silently accepted as progress.' },
  { construct: 'EnableNotebookOptions.preconditions', status: 'adopt_backlog', note: 'v6.6.0 simodelne/pgas#1209/#1210 adds EnableNotebookOptions.preconditions: Partial<Record<NotebookActionName, Predicate[]>> -- consumer-owned admissibility predicates attached to record_note/pin_note/unpin_note/delete_note in every targeted mode and evaluated by the ordinary GKPrecondition gate; the convention notebook: sidecar accepts the same key. Anchors node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:9643 (NotebookActionName), 9644-9688 (EnableNotebookOptions, preconditions at 9687), 9689 (enableNotebook); plugin.d.ts:54,62,181. The foundry\'s own program deliberately does not call enableNotebook (src/foundry-program/registration.ts:59-74), but the generated governed-attach profile calls enableNotebook(loadedSpec, { modes: [...] }) at src/pgas-new/governed-attach-profile.ts:352 WITHOUT preconditions -- the option is NOT EMITTED (0 hits for a preconditions key on enableNotebook in src/ and templates/) -- so it inherits the 6.2.0-6.6.0 notebook changes (record_note now carries mset_must_change, delete_note MClears instead of MSet \'\', pin/unpin gained argSchema key) ungated. Emission opportunity: pass preconditions gating the four notebook actions per mode from the attach profile\'s stage graph.' },
  { construct: 'action_map.result_collection', status: 'adopt_backlog', note: 'v6.4.0 simodelne/pgas#1061 (CLOSED 2026-08-31) adds ResultCollectionDecl { path, items_path?, max_items 1..10000 }: action-local bounded accumulation from a successful Sync Out result into an exact authored ArrayType target, settled atomically alongside result_path; loader requires a present declared Sync Out channel and (TC-5) a tool result_collection equal to its action\'s. Anchors node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:1251-1258 (ResultCollectionDecl), 1657 (ActionSemantics.result_collection), 3218 (raw), 24/46 (tool declaration); plugin.d.ts:110. Not emitted (0 hits for result_collection in src/ and templates/) although the foundry emits result_path on every tool/composite action (191 hits in src/ + templates/) and research/scrape-style programs accumulate result lists in TS handlers. Emission opportunity: emit result_collection next to result_path for web_search/composite stages whose stage-output contract declares a record_array, deleting the hand-rolled accumulation handler.' },
  { construct: 'Feature.result_collection', status: 'adopt_backlog', note: 'v6.4.0 simodelne/pgas#1061 Feature flag gating action_map.result_collection; Feature union at node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:315 (verified against 6.6.1). Not emitted (0 hits); flips together with action_map.result_collection.' },
  { construct: 'ProgramEntry.manifest', status: 'adopt_backlog', note: 'v6.5.0 simodelne/pgas#1144 (CLOSED 2026-08-31) made ProgramManifest { description, keywords, interactive? } declarable as a top-level manifest: YAML sidecar consumed by loadProgramByConvention (validated and stripped before compile; declaring it in YAML AND entryOverrides fails the load, RegisterProgramByConventionOptions doc at 10093-10106). Anchors node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:5857-5861 (ProgramManifest), 6005 (ProgramEntry.manifest). Not emitted as YAML: standalone convention-loaded programs declare no manifest:, and the governed-attach profile hand-generates ProgramEntry.manifest as TS at src/pgas-new/governed-attach-profile.ts:281-285,363 on a loadSpecWithPatterns entry. Emission opportunity: serialize manifest: into specs.yml for convention-loaded programs and drop the generated TS constant.' },
  { construct: 'ProgramEntry.presentation', status: 'adopt_backlog', note: 'v6.5.0 simodelne/pgas#1144 made ProgramPresentation (labels for program/modes/channels/actions/paths, context tabs) declarable as a top-level presentation: YAML sidecar alongside manifest: and policies.{surrogatePolicy,uploadContentPolicy,surrogateProgramPolicy}. Anchors node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:5862-5880 (ProgramPresentationContextTab, ProgramPresentation), 6006 (ProgramEntry.presentation). Not emitted as YAML; the governed-attach profile hand-generates ProgramEntry.presentation and ProgramEntry.surrogatePolicy as TS at src/pgas-new/governed-attach-profile.ts:287-366. Emission opportunity: same YAML sidecar move as ProgramEntry.manifest.' },
  { construct: 'ConventionProgramFamilyLoad.registrations', status: 'available_unused', note: 'v6.5.0 simodelne/pgas#1144 adds top-level registrations: (public/service aliases of one compiled source) materialized by loadProgramFamilyByConvention/registerProgramFamilyByConvention into ConventionProgramRegistration[] and admitted atomically through ProgramRegistry.registerBatch. Anchors node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:10120-10130 (ConventionProgramRegistration, ConventionProgramFamilyLoad.registrations 10129), 10133/10135 (family loaders), 6114 (registerBatch); plugin.d.ts:41,188,203. Not emitted (0 spec-level hits for registrations in src/ and templates/); every generated program registers under exactly one name, so no family is needed today; emit-on-demand when a synthesized program needs a service-role alias.' },
  { construct: 'PgasServerConfig.capabilityConfigs', status: 'adopt_backlog', note: 'v6.4.0 simodelne/pgas#1132 (CLOSED 2026-08-30) adds deployment-owned capability configuration: PgasServerConfig extends CapabilityConfigPgasServerOption { capabilityConfigs?: CapabilityConfigRegistration[] } where each registration is { ref, config: CapabilityDeploymentConfig } and capability:/composite: channel bindings carry ConfiguredCapabilityBinding.configRef; RagSearchCapabilityConfigV1 (endpoint, bearerToken, partitionIds?, timeouts) is the only config kind in 6.6.1. Anchors node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:8902-8921 (CapabilityBindingMap, ConfiguredCapabilityBinding, CapabilityConfigRegistration, RagSearchCapabilityConfigV1, CapabilityDeploymentConfig), 8943-8946 (option + PgasServerConfig); create-server.d.ts:16-17,24. Not emitted (0 hits for capabilityConfigs/RagSearch in src/ and templates/); generated server.ts passes only programs/devMode/roundTimeoutMs/drivers and the foundry still tracks web_search/document_extraction capabilities as adopt_backlog. Emission opportunity: when the engine-capability migration lands, emit capabilityConfigs in the standalone server.ts.tmpl from a deployment env block instead of per-program tool adapters.' },
  { construct: 'PgasServerConfig.telemetry.authorSink', status: 'available_unused', note: 'v6.3.0 simodelne/pgas#1115 (CLOSED 2026-08-30) adds the opt-in trusted author telemetry sink: telemetry.authorSink: AuthorTelemetrySink receives AuthorPromptTelemetryEvent (llm.prompt.raw) / AuthorCallEndTelemetryEvent (llm.call.end); raw content is denied unless rawAuthorContentPolicy returns true; injected JSON author handles need resolveJsonAuthorIdentity. Anchors node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:8768-8805 (AuthorIdentityContext, AuthorIdentityResolver, AuthorPromptTelemetryEvent, AuthorCallEndTelemetryEvent, AuthorTelemetryEvent, AuthorTelemetrySink), 9330-9340 (telemetry option); create-server.d.ts:11-15. Deployment-optional and orthogonal to synthesis: the foundry passes telemetry: { enabled: false } (src/pgas-new/template-renderer.ts) and the sink is NOT EMITTED (0 hits for authorSink/AuthorTelemetry in src/ and templates/). Emission opportunity: expose an optional authorSink hook in the standalone server.ts.tmpl for operators who want per-call author observability.' },
  { construct: 'Predicate.ClaimsSupportedBySource', status: 'available_unused', note: 'v6.4.0 simodelne/pgas#1083 semantic entailment v2 (child propagation #1179 in 6.5.2; untouched-key skip in 6.5.4): schema-invariant leaf whose verdict comes from a registered SemanticEntailmentProvider (protocol 1|2, ProviderCallOptions.requestVersion, failure provider_incompatible), with the keyed evidence mode keys keyed_evidence_path/evidence_item_path/evidence_status_path/evidence_supported_value. Anchors node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:268 (PredicateKind), 105-131 (settlement/provider types), 1027-1057 (predicate fields), 315 (Feature.semantic_entailment). N-A today: the foundry emits no ClaimsSupportedBySource and registers no provider (0 hits in src/ and templates/); the emitted grounding predicates are FieldSourceGrounded/FieldMatchesPattern.' },
  { construct: 'Predicate.StringTrimmedLengthAtLeast', status: 'available_unused', note: 'PredicateKind member with min as the inclusive trimmed-length lower bound (1..1_000_000); anchors (verified against 6.6.1) node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:268 and min docs at 1088-1094. Not emitted; no generated descriptor needs a non-blank-text floor yet, though confirmation-loop proposal content args are the natural home if one is added.' },
  { construct: 'derived_paths.offset_of/product_of/quotient_of', status: 'available_unused', note: 'pgas#844.4 arithmetic DerivedPathSetKind members (offset_of adds a finite literal, negative for subtraction; product_of/quotient_of scale); anchors (verified against 6.6.1) node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:1945 (DerivedPathSetKind), 2032-2043 (parameter docs), 3458 (raw). Not emitted (0 hits); collection-lifecycle synthesis emits sum_of/count_of only and has no descriptor for scaled or offset totals.' },
  { construct: 'Feature.sync_out_resilience', status: 'available_unused', note: 'Feature flag plus Channel.resilience: SyncOutResiliencePolicy for Sync Out channels; anchors (verified against 6.6.1) node_modules/@simodelne/pgas-server/dist-bundle/_shared-types.d.ts:315 (Feature), 627 (Channel.resilience), 3116 (raw). Not emitted (0 hits); generated Sync Out tool channels rely on policies.syncOutContinuationPolicy instead.' },
] as const;

export const ENGINE_PRIMITIVE_REGISTRY: readonly EnginePrimitiveEntry[] = [
  {
    computation_class: 'iteration_cursor',
    primitive_index: 1,
    primitive_name: 'first_item_where_field_ne',
    primitive_status: 'landed',
    pgas_ref: 'simodelne/pgas#829',
    request_ref: CONVERGENCE_ALIGNMENT_REQUEST,
    foundry_enforcement: 'active',
    since_engine_version: '3.28.0',
    build_order_note: 'Adopted after #3 keyed_by landed; confirmation-loop indexed collections keep status and terminal marker on the scanned collection.',
  },
  {
    computation_class: 'completion_guard',
    primitive_index: 2,
    primitive_name: 'all_items_field_eq',
    primitive_status: 'landed',
    pgas_ref: 'simodelne/pgas#831',
    request_ref: 'docs/curator-requests/2026-08-06-completion-predicate.md',
    foundry_enforcement: 'active',
    since_engine_version: '3.29.0',
    build_order_note: 'Narrow completion_guard class split from broad domain_shape_branch to avoid refusing ordinary domain branching while enforcing all-items completion equality.',
  },
  {
    computation_class: 'compute_dedup',
    primitive_index: 3,
    primitive_name: 'keyed_by',
    primitive_status: 'landed',
    pgas_ref: 'simodelne/pgas#831 roadmap',
    request_ref: 'docs/curator-requests/2026-08-06-keyed-idempotent-collection.md',
    foundry_enforcement: 'active',
    since_engine_version: '3.29.0',
    build_order_note: 'Linchpin primitive; foundry keeps compute_dedup enforcement active and emits keyed_collections instead of imperative dedup.',
  },
  {
    computation_class: 'numeric_validation',
    primitive_index: 4,
    primitive_name: 'numeric_comparison_predicate',
    primitive_status: 'landed',
    pgas_ref: 'simodelne/pgas#831',
    request_ref: CONVERGENCE_ALIGNMENT_REQUEST,
    foundry_enforcement: 'active',
    since_engine_version: '3.30.0',
    build_order_note: 'Narrowed from broad adhoc_validation_throw to numeric threshold/coherence validation only; structural validation remains detected but has no landed primitive.',
  },
  {
    computation_class: 'recovery_steer',
    primitive_index: 5,
    primitive_name: 'recovery_steer',
    primitive_status: 'landed',
    pgas_ref: 'simodelne/pgas#831',
    request_ref: CONVERGENCE_ALIGNMENT_REQUEST,
    foundry_enforcement: 'active',
    since_engine_version: '3.30.0',
    build_order_note: 'Confirmation-loop per-round recovery guidance emits recovery_steers; 3.32.0 enrichment now uses idempotent set and template_paths for derived active-item cursor guidance.',
  },
  {
    computation_class: 'existential_completion_guard',
    primitive_index: 6,
    primitive_name: 'any_item_field_eq',
    primitive_status: 'landed',
    pgas_ref: 'simodelne/pgas#844',
    request_ref: CONVERGENCE_ALIGNMENT_REQUEST,
    foundry_enforcement: 'active',
    since_engine_version: '3.32.0',
    build_order_note: 'Narrow existential completion flag over collection field equality; emitted from the same derived-path helper as all_items_field_eq.',
  },
  {
    computation_class: 'partition_by_verdict',
    primitive_index: 7,
    primitive_name: 'items_where_field_eq',
    primitive_status: 'landed',
    pgas_ref: 'simodelne/pgas#844',
    request_ref: CONVERGENCE_ALIGNMENT_REQUEST,
    foundry_enforcement: 'active',
    since_engine_version: '3.32.0',
    build_order_note: 'Narrow partition-by-verdict buckets for approval flows; broad filter/group reshaping remains outside this class.',
  },
  {
    computation_class: 'numeric_aggregate',
    primitive_index: 8,
    primitive_name: 'sum_of',
    primitive_status: 'landed',
    pgas_ref: 'simodelne/pgas#844',
    request_ref: CONVERGENCE_ALIGNMENT_REQUEST,
    foundry_enforcement: 'active',
    since_engine_version: '3.32.0',
    build_order_note: 'Narrow numeric sum aggregation over indexed collection item fields; non-sum grouping/aggregation remains refused as compute_aggregate.',
  },
  {
    computation_class: 'token_coverage_validation',
    primitive_index: 9,
    primitive_name: 'FieldContainsAll',
    primitive_status: 'landed',
    pgas_ref: 'simodelne/pgas#844',
    request_ref: CONVERGENCE_ALIGNMENT_REQUEST,
    foundry_enforcement: 'active',
    since_engine_version: '3.32.0',
    build_order_note: 'Narrow authored-text required-token coverage validation; other structural validation throws remain outside this primitive.',
  },
  {
    computation_class: 'content_key_merge',
    primitive_index: 10,
    primitive_name: 'merge_collections',
    primitive_status: 'landed',
    pgas_ref: 'simodelne/pgas#844',
    request_ref: CONVERGENCE_ALIGNMENT_REQUEST,
    foundry_enforcement: 'pending',
    since_engine_version: '3.32.0',
    build_order_note: 'Register-only adoption: no foundry content-key merge emitter exists today; keyed persistence continues to use keyed_collections, so merge_collections enforcement stays pending until a content-key reducer emitter is introduced.',
  },
  {
    computation_class: 'regex_validation',
    primitive_index: 11,
    primitive_name: 'FieldMatchesPattern/FieldNotMatchesPattern',
    primitive_status: 'landed',
    pgas_ref: 'simodelne/pgas#862',
    request_ref: CONVERGENCE_ALIGNMENT_REQUEST,
    foundry_enforcement: 'active',
    since_engine_version: '3.34.0',
    build_order_note: 'Narrow regex-pattern validation over extracted document record text; foundry emits FieldMatchesPattern/FieldNotMatchesPattern in schema_invariants and refuses imperative RegExp validation in stage bodies.',
  },
  {
    computation_class: 'source_grounding_validation',
    primitive_index: 12,
    primitive_name: 'FieldSourceGrounded',
    primitive_status: 'landed',
    pgas_ref: 'simodelne/pgas#862',
    request_ref: CONVERGENCE_ALIGNMENT_REQUEST,
    foundry_enforcement: 'active',
    since_engine_version: '3.34.0',
    build_order_note: 'Narrow anti-fabrication validation for extracted document records; foundry emits FieldSourceGrounded in schema_invariants with engine-owned token extractors and source allowlist paths.',
  },
  {
    computation_class: 'arg_schema',
    primitive_index: 13,
    primitive_name: 'arg_schema',
    primitive_status: 'landed',
    pgas_ref: 'simodelne/pgas#891',
    request_ref: CONVERGENCE_ALIGNMENT_REQUEST,
    foundry_enforcement: 'active',
    since_engine_version: '4.2.0',
    build_order_note: 'Generated contracted reasoning actions, notebook pin/unpin actions, and confirmation-loop proposal actions emit action_map.arg_schema from existing contract/lifecycle/sentinel arg constraints; free-form reasoning and wildcard notebook actions remain unconstrained.',
  },
  {
    computation_class: 'no_action_escape',
    primitive_index: 14,
    primitive_name: 'no_action_escapes',
    primitive_status: 'landed',
    pgas_ref: 'simodelne/pgas#889',
    request_ref: CONVERGENCE_ALIGNMENT_REQUEST,
    foundry_enforcement: 'active',
    since_engine_version: '4.2.0',
    build_order_note: 'Confirmation-loop authoring modes emit no_action_escapes with engine-owned counter/arm paths; the arm gates a blocked terminal route and disables further proposal attempts rather than auto-approving unresolved items. Complements recovery_steers: recovery_steers arm on predicates, no_action_escapes arm on fallback-round count, both arm-only.',
  },
] as const;

export function primitiveForConstruct(kind: EnginePrimitiveConstructKind): EnginePrimitiveEntry | undefined {
  return ENGINE_PRIMITIVE_REGISTRY.find((entry) => entry.computation_class === kind);
}

export function activeEnforcedConstructs(
  registry: readonly EnginePrimitiveEntry[] = ENGINE_PRIMITIVE_REGISTRY,
): ReadonlySet<GovernedConstructKind> {
  return new Set(
    registry
      .filter((entry): entry is EnginePrimitiveEntry & { computation_class: GovernedConstructKind } =>
        entry.foundry_enforcement === 'active' && isGovernedConstructKind(entry.computation_class))
      .map((entry) => entry.computation_class),
  );
}

export function refusedConstructs(
  registry: readonly EnginePrimitiveEntry[] = ENGINE_PRIMITIVE_REGISTRY,
): ReadonlySet<GovernedConstructKind> {
  return new Set(
    registry
      .filter((entry): entry is EnginePrimitiveEntry & { computation_class: GovernedConstructKind } =>
        entry.foundry_enforcement === 'active' &&
        entry.primitive_status !== 'landed' &&
        isGovernedConstructKind(entry.computation_class))
      .map((entry) => entry.computation_class),
  );
}

function isGovernedConstructKind(kind: EnginePrimitiveConstructKind): kind is GovernedConstructKind {
  return kind !== 'arg_schema' && kind !== 'no_action_escape';
}
